targets:
  $default:
    builders:
      builder_examples|aggregation_builder:
        enabled: true
        options:
          filename: aggregated

builders:
  builder_examples|aggregation_builder:
    import: 'package:builder_examples/aggregation_builder.dart'
    builder_factories: ['aggregationBuilder']
    build_extensions:
      $lib$:
      - .dart
    auto_apply: dependents
    build_to: source
