name: builder_examples
description: Builder examples.
version: 1.0.0+2

environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  build: ^2.0.0
  glob: ^2.0.1
  path: ^1.8.0
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.10.6
  pedantic: ^1.11.0
  test: ^1.16.8
