name: builder_examples
description: Builder examples.
version: 1.0.0+3

environment:
  sdk: '>=2.15.2 <3.0.0'

dependencies:
  build: ^2.1.1
  glob: ^2.0.2
  path: ^1.8.0
  source_gen: ^1.1.1

dev_dependencies:
  build_runner: ^2.1.5
  pedantic: ^1.11.1
  test: ^1.19.4
